In [2]:
#link to tutorial: https://keras.io/examples/timeseries/timeseries_classification_transformer/

In [3]:
import numpy as np 

In [5]:
# creating a file read function 
def read_data_file(filename):
  dataset = np.loadtxt(filename, delimiter="\t")
  y = dataset[:, 0]
  x = dataset[:, 1:]
  return x, y.astype(int)

In [6]:
dataset_url = "https://raw.githubusercontent.com/hfawaz/cd-diagram/master/FordA/"

In [8]:
# read the dataset and split it into training data and test dataset
x_training_set, y_training_set = read_data_file(dataset_url + "FordA_TRAIN.tsv")
x_test_set, y_test_set = read_data_file(dataset_url + "FordA_TEST.tsv")

In [11]:
# validating the data was read properly
x_training_set

array([[-0.79717168, -0.66439208, -0.37301463, ..., -0.66439208,
        -1.0737958 , -1.5643427 ],
       [ 0.80485472,  0.63462859,  0.37347448, ..., -0.71488505,
        -0.56044294, -0.31908642],
       [ 0.7279851 ,  0.11128392, -0.49912439, ...,  0.39446303,
         0.33940042,  0.25539062],
       ...,
       [-0.57005428, -0.33316523, -0.29351853, ..., -1.3937145 ,
        -0.94273327, -0.27072168],
       [ 2.0067321 ,  2.0791499 ,  2.0220362 , ..., -0.43214504,
        -0.44123126, -0.28070891],
       [-0.12524091, -0.32536268, -0.48823697, ...,  0.55576053,
         0.57445102,  0.57311598]])

In [12]:
y_training_set

array([-1,  1, -1, ..., -1,  1, -1])

In [13]:
x_test_set

array([[-0.14040239,  0.17164128,  0.30204415, ..., -0.69040244,
        -0.97659635, -0.79426313],
       [ 0.33403756,  0.32225332,  0.45384397, ..., -1.0417721 ,
        -1.1596145 , -1.3756589 ],
       [ 0.71668608,  0.74436655,  0.72591291, ..., -3.6752806 ,
        -4.1366217 , -4.3396117 ],
       ...,
       [ 0.71008362,  0.59397882,  0.3818858 , ..., -0.12655282,
        -0.11782239, -0.18909413],
       [ 0.00684706, -0.14062427, -0.27059412, ..., -1.0007084 ,
        -1.0841075 , -1.109963  ],
       [-0.54135529, -0.24172258,  0.10074086, ..., -0.09362504,
        -0.90080431, -1.778341  ]])

In [14]:
y_test_set

array([-1, -1, -1, ...,  1,  1,  1])

In [15]:
# next step is to reshape the training and test set into vectors 
x_training_set = x_training_set.reshape((x_training_set.shape[0], x_training_set.shape[1], 1))
x_test_set = x_test_set.reshape((x_test_set.shape[0], x_test_set.shape[1], 1))